### PR TITLE
platform: Install gpio, pwm as optional

### PR DESCRIPTION
**Pull request by rzr**
Change-Id: Ie6012c3edf1b2248943dbf1794038e6703fc5a5c
Signed-off-by: Philippe Coval <p.coval@samsung.com>

### CODE REVIEW

**Comment by mrstegeman** [comment]
I think `devDependencies` would be more appropriate, since this is just for example code. That's what I did for other example dependencies.

**Comment by rzr** [comment]
well I think otherwise, I see devdeps are build deps , here it's a runtime dependency for some sample apps (boards)

**Comment by mrstegeman** [comment]
I see your point, but if you add them as `optionalDependencies`, `npm` will try to install those packages anytime you install the `webthing` package, which is not really desired.

**Comment by rzr** [comment]
Yes I made mistake by updated wrong files, I guess the way it is OK as you merged my updated change.

Thanks

**Pull request merged**
