### PR TITLE
Return promise when starting server.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by jaller94** [comment]
This should be considered a API-breaking change as the returned promise will have to be handled outside the library when calling `server.start()`.

**Comment by mrstegeman** [comment]
I'd argue that it's not breaking the API. The function is returning a value now, instead of nothing. Behavior is identical, and invocation of `start()` doesn't change at all.

**Comment by jaller94** [comment]
But this is not a regular value. It is a promise and all promises have to be handled.
An error inside a promise might kill the process.

See https://nodejs.org/dist/latest-v8.x/docs/api/deprecations.html#deprecations_dep0018_unhandled_promise_rejections

**Comment by jaller94** [comment]
Yes, the behaviour does not change. However, now there is now an expectation for developers to catch possible errors.

I would appreciate an update to the examples and a hint in the release notes that there is a promise the library is forwarding.

Also, thanks so much for addressing the issue this quickly (and apparently at the sacrifice of your valuable sleep). This package makes developing valid WebThings with Websockets and network advertising super easy.

P.S. Version 0.8.0 has no tag on GitHub yet.

**Comment by mrstegeman** [comment]
r=me

**Pull request merged**
